### ISSUE TITLE
輸入 \ (單反斜線) 會被轉爲 \\ (雙反斜線)

### ISSUE THREAD

**Issue by Kotsuha** [WenyaoL/YaliEditor#4]
在IR模式輸入以下內容

```
%LOCALAPPDATA%\Microsoft\Windows\Shell
```

然後複製這段內容，到別的文字編輯器貼上，內容會變成

```
%LOCALAPPDATA%\\Microsoft\\Windows\\Shell
```

進入源碼模式看也變成 `\\` 的樣子

**Comment by WenyaoL** [comment]
因为（ctrl+c）复制时默认使用markdown格式，在DOM转markdown时默认做了转置（是编辑器内部的turndown插件转的）。
**项目现在还处于开发阶段，这个问题可能要下个小版本进行更改。**

**Comment by WenyaoL** [comment]
版本已经跟新，可以试试v1.1.2版，应该没有转置的问题了

**Comment by Kotsuha** [comment]
正常了
