### ISSUE TITLE
把md拖入鴨梨編輯器的行爲

### ISSUE THREAD

**Issue by Kotsuha** [WenyaoL/YaliEditor#6]
目前把md拖入鴨梨會插入一個鏈接。

我覺得非md的文件（例如圖片）拖入鴨梨插入鏈接很合理。
但如果是md文件拖進去，很可能使用者想要打開文件。也許可以讓它詢問要打開文件或插入鏈接；或普通操作是打開，特殊操作（譬如按著Shift拖進去）是插入鏈接。

**Comment by WenyaoL** [comment]
拖拽行为还在开发阶段，可能会有BUG，现在的拖拽行为默认当成图片链接处理。
下个版本拖拽行为和快捷键自定义设置功能一起更新。
**建议先别用拖拽功能**（等下个版本功能完善了再使用，免得出现bug）

**Comment by Kotsuha** [comment]
大佬更新好快，辛苦了~ 加油
順便也希望有切換源碼模式的快捷鍵

**Comment by Kotsuha** [comment]
用 [v2.2.0](https://github.com/WenyaoL/YaliEditor/releases/tag/v2.2.0) 測試沒問題，感謝！
